---
- name: Configure Nginx
  hosts: webservers
  become: true

  tasks:
    - name: Install Nginx on Ubunt/Debian systems
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      when: ansible_facts["os_family"] == "Debian"

    - name: Install Nginx on RedHat systems
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_facts["os_family"] == "RedHat"

    - name: Start Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true

    - name: Create website directory
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Create index page
      ansible.builtin.copy:
        content: "Hello from Ansible!"
        dest: "{{ web_root }}"/index.html
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Deploy Nginx configuration
      ansible.builtin.template:
        src: myapp.conf.j2
        dest: /etc/nginx/sites-available/myapp.conf
        owner: root
        group: root
        mode: "0644"
      notify: Reload Nginx

    - name: Enable Nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/myapp.conf
        dest: /etc/nginx/sites-enabled/myapp.conf
        state: link
      notify: Reload Nginx

    - name: Disable default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx

  handlers:

    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded